version: '1.0'

services:
  web-api:
    container_name: API-Python
    build: 
      context: .
    volumes:
      - ./src:/src
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    ports:
      - 5000:5000
